### ISSUE TITLE
GitHub title should read 20?

### ISSUE THREAD

**Issue by preagan** [jaredhanson/passport-google-oauth2#85]
A minor typo seems to be present in this repos' title.

Without the trailing zero, this one...
    jaredhanson / **passport-google-oauth2**
...seems to be a duplicate of that one...
    mstade / **passport-google-oauth2**

**Comment by preagan** [comment]
Just some confusion when coming from Passport strategies.  'Seems like an easy thing to fix to help newcomers.  Should this observation have been posted someplace else?

**Comment by jaredhanson** [comment]
I'm going to close this, since its not an issue or bug with the code.

The package name and repository URL are independent, and don't need to be the same.  I don't think this should cause confusion, but if I hear this feedback more often I'll consider changing it.

**Comment by preagan** [comment]
I'm confused... Is this not a simple fix?  Why not make it easier for someone to choose to use this code?

**Comment by jaredhanson** [comment]
What's the action you are proposing?  Should I rename this GitHub repository to add a `0` at the end?

**Comment by preagan** [comment]
Yes.  What am I missing that makes this complicated?  Would that cause some other problems?

**Comment by jaredhanson** [comment]
So, here's the story:

As with all code, I created a repository for this strategy when I started developing it.   I named it according to the conventions I like to follow for my personal repositories.   When it came time to publish to npm, the name `passport-google-oauth2` was already taken.   So, I named the package `passport-google-oauth20`.

I prefer to keep the repository named `passport-google-oauth2`, since that matches my own preferences in my development environment.   I don't think this is making it harder for anyone to use the code, but if you have a reason it is please let me know.

**Comment by preagan** [comment]
As a newcomer, such a thing looks like a typo.  But beyond causing a little bit of confusion, it sends that message that the author doesn't care about details and makes me wonder about the underlying code.  

Hey, I'm just trying to be helpful.  Suit yourself.
